//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projbook.Core.Projbook.Core.Model.Configuration.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projbook.Core.Projbook.Core.Model.Configuration.Validation.ConfigurationValidatio" +
                            "n", typeof(ConfigurationValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema&quot;,
        ///  &quot;type&quot;: &quot;array&quot;,
        ///  &quot;minItems&quot;: 1,
        ///  &quot;items&quot;: {
        ///    &quot;type&quot;: &quot;object&quot;,
        ///    &quot;anyOf&quot;: [
        ///      { &quot;required&quot;: [ &quot;template-html&quot; ] },
        ///      { &quot;required&quot;: [ &quot;template-pdf&quot; ] }
        ///    ],
        ///    &quot;required&quot;: [ &quot;title&quot; ],
        ///    &quot;properties&quot;: {
        ///      &quot;title&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///      &quot;template-html&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///      &quot;template-pdf&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///      &quot;output-html&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///      &quot;output-pdf&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigurationArraySchema {
            get {
                return ResourceManager.GetString("ConfigurationArraySchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema&quot;,
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;anyOf&quot;: [
        ///    { &quot;required&quot;: [ &quot;template-html&quot; ] },
        ///    { &quot;required&quot;: [ &quot;template-pdf&quot; ] }
        ///  ],
        ///  &quot;required&quot;: [ &quot;title&quot; ],
        ///  &quot;properties&quot;: {
        ///    &quot;title&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///    &quot;template-html&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///    &quot;template-pdf&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///    &quot;output-html&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///    &quot;output-pdf&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///    &quot;pages&quot;: {
        ///      &quot;type&quot;: &quot;array&quot;,
        ///      &quot;minItems&quot;: 1,
        ///      &quot;items&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigurationSchema {
            get {
                return ResourceManager.GetString("ConfigurationSchema", resourceCulture);
            }
        }
    }
}
