//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projbook.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpectedFullGenerationFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpectedFullGenerationFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projbook.Tests.Resources.ExpectedFullGenerationFiles", typeof(ExpectedFullGenerationFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Title&gt;Test title&lt;/Title&gt;
        ///    &lt;Id&gt;PageContentmd&lt;/Id&gt;
        ///    &lt;Title&gt;First page title&lt;/Title&gt;
        ///	&lt;PreSectionContent&gt;&lt;![CDATA[&lt;p&gt;Before section…&lt;/p&gt;
        ///]]&gt;&lt;/PreSectionContent&gt;
        ///	&lt;Sections&gt;
        ///        &lt;Section&gt;
        ///			&lt;Id&gt;PageContentmd-foo&lt;/Id&gt;
        ///			&lt;Title&gt;Foo&lt;/Title&gt;
        ///			&lt;Content&gt;
        ///				&lt;![CDATA[
        ///&lt;h1&gt;Foo&lt;/h1&gt;
        ///]]&gt;
        ///			&lt;/Content&gt;
        ///        &lt;/Section&gt;
        ///        &lt;Section&gt;
        ///			&lt;Id&gt;PageContentmd-sub-foo&lt;/Id&gt;
        ///			&lt;Title&gt;Sub-foo&lt;/Title&gt;
        ///			&lt;Content&gt;
        ///				&lt;![CDATA[
        ///&lt;h2&gt;Sub-foo&lt;/h2&gt;
        ///]]&gt;
        ///			&lt;/Content&gt;
        ///        &lt;/Section&gt;
        ///	&lt;/Sections&gt;
        ///    &lt;Id&gt;PageSnip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Title&gt;Test title - PDF&lt;/Title&gt;
        ///    &lt;Id&gt;PageContentmd&lt;/Id&gt;
        ///    &lt;Title&gt;First page title&lt;/Title&gt;
        ///	&lt;PreSectionContent&gt;&lt;![CDATA[&lt;p&gt;Before section…&lt;/p&gt;
        ///]]&gt;&lt;/PreSectionContent&gt;
        ///	&lt;Sections&gt;
        ///        &lt;Section&gt;
        ///			&lt;Id&gt;PageContentmd-foo&lt;/Id&gt;
        ///			&lt;Title&gt;Foo&lt;/Title&gt;
        ///			&lt;Content&gt;
        ///				&lt;![CDATA[
        ///&lt;h1&gt;Foo&lt;/h1&gt;
        ///]]&gt;
        ///			&lt;/Content&gt;
        ///        &lt;/Section&gt;
        ///        &lt;Section&gt;
        ///			&lt;Id&gt;PageContentmd-sub-foo&lt;/Id&gt;
        ///			&lt;Title&gt;Sub-foo&lt;/Title&gt;
        ///			&lt;Content&gt;
        ///				&lt;![CDATA[
        ///&lt;h2&gt;Sub-foo&lt;/h2&gt;
        ///]]&gt;
        ///			&lt;/Content&gt;
        ///        &lt;/Section&gt;
        ///	&lt;/Sections&gt;
        ///    &lt;Id&gt;Pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simple_pdf {
            get {
                return ResourceManager.GetString("Simple_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Title&gt;Test title&lt;/Title&gt;
        ///&lt;OutputHtml&gt;doc.html&lt;/OutputHtml&gt;.
        /// </summary>
        internal static string SimpleIndex {
            get {
                return ResourceManager.GetString("SimpleIndex", resourceCulture);
            }
        }
    }
}
