//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projbook.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpectedCSharpFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpectedCSharpFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projbook.Tests.Resources.ExpectedCSharpFiles", typeof(ExpectedCSharpFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class A
        ///{
        ///    // In NS.NS2.NS3
        ///}
        ///
        ///class A
        ///{
        ///    // In NS2.NS2.NS3
        ///}.
        /// </summary>
        internal static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Projbook.Tests.Resources.SourcesA
        ///{
        ///    public class AnyClass
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string AnyClass {
            get {
                return ResourceManager.GetString("AnyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int[] fieldArray;.
        /// </summary>
        internal static string ArrayField {
            get {
                return ResourceManager.GetString("ArrayField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class Options
        ///{
        ///    // ...
        ///}.
        /// </summary>
        internal static string BlockOnlyClass {
            get {
                return ResourceManager.GetString("BlockOnlyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void EmptyMethod(string i){
        ///    // ...
        ///}.
        /// </summary>
        internal static string BlockOnlyEmptyMethod {
            get {
                return ResourceManager.GetString("BlockOnlyEmptyMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Some comment that needs to { be } escaped.
        ////// &lt;/summary&gt;
        ///public class ConflictingCommentsClass{
        ///    // ...
        ///}.
        /// </summary>
        internal static string BlockOnlyEscapedClass {
            get {
                return ResourceManager.GetString("BlockOnlyEscapedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;
        ////// Some comment that needs to { be } escaped.
        ////// &lt;/summary&gt;
        ///public class ConflictingCommentsClass2
        ///{
        ///    // ...
        ///}.
        /// </summary>
        internal static string BlockOnlyEscapedClass2 {
            get {
                return ResourceManager.GetString("BlockOnlyEscapedClass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public void Method([Test(&quot;Value that needs to { be } escaped&quot;)] string p){
        ///    // ...
        ///}.
        /// </summary>
        internal static string BlockOnlyEscapedMethod {
            get {
                return ResourceManager.GetString("BlockOnlyEscapedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public void Method([Test(&quot;Value that needs to { be } escaped&quot;)] string p)
        ///{
        ///    // ...
        ///}.
        /// </summary>
        internal static string BlockOnlyEscapedMethod2 {
            get {
                return ResourceManager.GetString("BlockOnlyEscapedMethod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event Action Event
        ///{
        ///    // ...
        ///}.
        /// </summary>
        internal static string BlockOnlyEvent {
            get {
                return ResourceManager.GetString("BlockOnlyEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add
        ///{
        ///    // ...
        ///}.
        /// </summary>
        internal static string BlockOnlyEventadd {
            get {
                return ResourceManager.GetString("BlockOnlyEventadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void Method()
        ///{
        ///    // ...
        ///}.
        /// </summary>
        internal static string BlockOnlyMethod {
            get {
                return ResourceManager.GetString("BlockOnlyMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public int Property {
        ///    // ...
        ///}.
        /// </summary>
        internal static string BlockOnlyProperty {
            get {
                return ResourceManager.GetString("BlockOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B(int foo)
        ///{
        ///}.
        /// </summary>
        internal static string Constructor {
            get {
                return ResourceManager.GetString("Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void Method()
        ///{
        ///    // Some content
        ///}
        ///
        ///void EmptyMethod(string i){}
        ///
        ///public int Property { get; set; }
        ///
        ///event Action Event
        ///{
        ///    add
        ///    {
        ///        // Something
        ///    }
        ///    remove
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string ContentOnlyClass {
            get {
                return ResourceManager.GetString("ContentOnlyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public void Method([Test(&quot;Value that needs to { be } escaped&quot;)] string p){
        ///    Console.WriteLine(&quot;Some code&quot;);
        ///}.
        /// </summary>
        internal static string ContentOnlyEscapedClass {
            get {
                return ResourceManager.GetString("ContentOnlyEscapedClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public void Method([Test(&quot;Value that needs to { be } escaped&quot;)] string p)
        ///{
        ///    Console.WriteLine(&quot;Some code&quot;);
        ///}.
        /// </summary>
        internal static string ContentOnlyEscapedClass2 {
            get {
                return ResourceManager.GetString("ContentOnlyEscapedClass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.WriteLine(&quot;Some code&quot;);.
        /// </summary>
        internal static string ContentOnlyEscapedMethod {
            get {
                return ResourceManager.GetString("ContentOnlyEscapedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add
        ///{
        ///    // Something
        ///}
        ///remove
        ///{
        ///}.
        /// </summary>
        internal static string ContentOnlyEvent {
            get {
                return ResourceManager.GetString("ContentOnlyEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Something.
        /// </summary>
        internal static string ContentOnlyEventadd {
            get {
                return ResourceManager.GetString("ContentOnlyEventadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Some content.
        /// </summary>
        internal static string ContentOnlyMethod {
            get {
                return ResourceManager.GetString("ContentOnlyMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get; set;.
        /// </summary>
        internal static string ContentOnlyProperty {
            get {
                return ResourceManager.GetString("ContentOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~B()
        ///{
        ///}.
        /// </summary>
        internal static string Destructor {
            get {
                return ResourceManager.GetString("Destructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public event Action Event
        ///{
        ///    add
        ///    {
        ///        // Add content
        ///    }
        ///    remove
        ///    {
        ///        // Remove content
        ///    }
        ///}.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add
        ///{
        ///    // Add content
        ///}.
        /// </summary>
        internal static string Eventadd {
            get {
                return ResourceManager.GetString("Eventadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove
        ///{
        ///    // Remove content
        ///}.
        /// </summary>
        internal static string Eventremove {
            get {
                return ResourceManager.GetString("Eventremove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool aFieldSomewhere, anotherFieldSomewhere;.
        /// </summary>
        internal static string FieldSomewhere {
            get {
                return ResourceManager.GetString("FieldSomewhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected bool Foo(string foo)
        ///{
        ///    return true;
        ///}
        ///
        ///protected bool Foo(string foo, int bar)
        ///{
        ///    return false;
        ///}.
        /// </summary>
        internal static string Foo {
            get {
                return ResourceManager.GetString("Foo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected bool Foo(string foo)
        ///{
        ///    return true;
        ///}.
        /// </summary>
        internal static string FooString {
            get {
                return ResourceManager.GetString("FooString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected bool Foo(string foo, int bar)
        ///{
        ///    return false;
        ///}.
        /// </summary>
        internal static string FooStringInt {
            get {
                return ResourceManager.GetString("FooStringInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class C&lt;T, U&gt;
        ///{
        ///    void CMethod&lt;X, Y&gt;(X x, Y y)
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string GenericClass {
            get {
                return ResourceManager.GetString("GenericClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void CMethod&lt;X, Y&gt;(X x, Y y)
        ///{
        ///}.
        /// </summary>
        internal static string GenericMethod {
            get {
                return ResourceManager.GetString("GenericMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get
        ///{
        ///    return 42;
        ///}
        ///
        ///get
        ///{
        ///    return 51;
        ///}.
        /// </summary>
        internal static string get {
            get {
                return ResourceManager.GetString("get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface I
        ///{
        ///    void InterfaceMethod(bool v1, string v2, int v3);
        ///}.
        /// </summary>
        internal static string I {
            get {
                return ResourceManager.GetString("I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void InterfaceMethod(bool v1, string v2, int v3);.
        /// </summary>
        internal static string IMethod {
            get {
                return ResourceManager.GetString("IMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public int this[string s, int i]
        ///{
        ///    get
        ///    {
        ///        return 51;
        ///    }
        ///    set
        ///    {
        ///        string bar = &quot;bar&quot;;
        ///    }
        ///}.
        /// </summary>
        internal static string Indexer {
            get {
                return ResourceManager.GetString("Indexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get
        ///{
        ///    return 51;
        ///}.
        /// </summary>
        internal static string Indexerget {
            get {
                return ResourceManager.GetString("Indexerget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set
        ///{
        ///    string bar = &quot;bar&quot;;
        ///}.
        /// </summary>
        internal static string Indexerset {
            get {
                return ResourceManager.GetString("Indexerset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///
        ///    
        ///    // Some comments here
        ///
        ///    using System;
        ///
        ///    namespace Projbook.Tests.Resources.SourcesA
        ///    {
        ///        public class NeedCleanup
        ///        {
        ///            // Following is an empty line
        /// 
        ///            // That has to be kept without preventing the indent fix
        ///        }
        ///    }
        ///
        ///    // Some more fucky lines after
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string NeedCleanup {
            get {
                return ResourceManager.GetString("NeedCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class NeedCleanup
        ///{
        ///    // Following is an empty line
        ///
        ///    // That has to be kept without preventing the indent fix
        ///}.
        /// </summary>
        internal static string NeedCleanupClass {
            get {
                return ResourceManager.GetString("NeedCleanupClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace NS
        ///{
        ///    public class OneClassSomewhere
        ///    {
        ///        private class SubClass
        ///        {
        ///            public int WhateverProperty
        ///            {
        ///                get
        ///                {
        ///                    return 42;
        ///                }
        ///                set
        ///                {
        ///                    string foo = &quot;foo&quot;;
        ///                }
        ///            }
        ///        }
        ///
        ///        protected bool Foo(string foo)
        ///        {
        ///            return true;
        ///        }
        ///
        ///        protected bool Foo(string foo, int bar)
        ///        {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NS {
            get {
                return ResourceManager.GetString("NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace NS2
        ///{
        ///    namespace NS2.NS3
        ///    {
        ///        class A
        ///        {
        ///            // In NS2.NS2.NS3
        ///        }
        ///
        ///        class B
        ///        {
        ///            B(int foo)
        ///            {
        ///            }
        ///
        ///            ~B()
        ///            {
        ///            }
        ///        }
        ///
        ///        class C&lt;T, U&gt;
        ///        {
        ///            void CMethod&lt;X, Y&gt;(X x, Y y)
        ///            {
        ///            }
        ///        }
        ///
        ///        class D
        ///        {
        ///            public int this[string s, int i]
        ///            {
        ///                get
        ///                {
        ///                    return 51;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NS2 {
            get {
                return ResourceManager.GetString("NS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace NS2.NS3
        ///{
        ///    class A
        ///    {
        ///        // In NS2.NS2.NS3
        ///    }
        ///
        ///    class B
        ///    {
        ///        B(int foo)
        ///        {
        ///        }
        ///
        ///        ~B()
        ///        {
        ///        }
        ///    }
        ///
        ///    class C&lt;T, U&gt;
        ///    {
        ///        void CMethod&lt;X, Y&gt;(X x, Y y)
        ///        {
        ///        }
        ///    }
        ///
        ///    class D
        ///    {
        ///        public int this[string s, int i]
        ///        {
        ///            get
        ///            {
        ///                return 51;
        ///            }
        ///            set
        ///            {
        ///                string bar = &quot;bar&quot;;
        ///            }
        ///        }
        ///
        ///        public event Act [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NS2NS2NS3 {
            get {
                return ResourceManager.GetString("NS2NS2NS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class A
        ///{
        ///    // In NS2.NS2.NS3
        ///}.
        /// </summary>
        internal static string NS2NS2NS3A {
            get {
                return ResourceManager.GetString("NS2NS2NS3A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace NS2.NS3
        ///{
        ///    class A
        ///    {
        ///        // In NS.NS2.NS3
        ///    }
        ///}
        ///
        ///namespace NS2.NS3
        ///{
        ///    class A
        ///    {
        ///        // In NS2.NS2.NS3
        ///    }
        ///
        ///    class B
        ///    {
        ///        B(int foo)
        ///        {
        ///        }
        ///
        ///        ~B()
        ///        {
        ///        }
        ///    }
        ///
        ///    class C&lt;T, U&gt;
        ///    {
        ///        void CMethod&lt;X, Y&gt;(X x, Y y)
        ///        {
        ///        }
        ///    }
        ///
        ///    class D
        ///    {
        ///        public int this[string s, int i]
        ///        {
        ///            get
        ///            {
        ///                return 51;
        ///            }
        ///            set
        ///            {
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NS2NS3 {
            get {
                return ResourceManager.GetString("NS2NS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace NS2.NS3
        ///{
        ///    class A
        ///    {
        ///        // In NS.NS2.NS3
        ///    }
        ///}.
        /// </summary>
        internal static string NSNS2NS3 {
            get {
                return ResourceManager.GetString("NSNS2NS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class A
        ///{
        ///    // In NS.NS2.NS3
        ///}.
        /// </summary>
        internal static string NSNS2NS3A {
            get {
                return ResourceManager.GetString("NSNS2NS3A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public class OneClassSomewhere
        ///{
        ///    private class SubClass
        ///    {
        ///        public int WhateverProperty
        ///        {
        ///            get
        ///            {
        ///                return 42;
        ///            }
        ///            set
        ///            {
        ///                string foo = &quot;foo&quot;;
        ///            }
        ///        }
        ///    }
        ///
        ///    protected bool Foo(string foo)
        ///    {
        ///        return true;
        ///    }
        ///
        ///    protected bool Foo(string foo, int bar)
        ///    {
        ///        return false;
        ///    }
        ///}.
        /// </summary>
        internal static string OneClassSomewhere {
            get {
                return ResourceManager.GetString("OneClassSomewhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set
        ///{
        ///    string foo = &quot;foo&quot;;
        ///}
        ///
        ///set
        ///{
        ///    string bar = &quot;bar&quot;;
        ///}.
        /// </summary>
        internal static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private class SubClass
        ///{
        ///    public int WhateverProperty
        ///    {
        ///        get
        ///        {
        ///            return 42;
        ///        }
        ///        set
        ///        {
        ///            string foo = &quot;foo&quot;;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string SubClass {
            get {
                return ResourceManager.GetString("SubClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public int WhateverProperty
        ///{
        ///    get
        ///    {
        ///        return 42;
        ///    }
        ///    set
        ///    {
        ///        string foo = &quot;foo&quot;;
        ///    }
        ///}.
        /// </summary>
        internal static string WhateverProperty {
            get {
                return ResourceManager.GetString("WhateverProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get
        ///{
        ///    return 42;
        ///}.
        /// </summary>
        internal static string WhateverPropertyget {
            get {
                return ResourceManager.GetString("WhateverPropertyget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set
        ///{
        ///    string foo = &quot;foo&quot;;
        ///}.
        /// </summary>
        internal static string WhateverPropertyset {
            get {
                return ResourceManager.GetString("WhateverPropertyset", resourceCulture);
            }
        }
    }
}
