//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projbook.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpectedXmlFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpectedXmlFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projbook.Tests.Resources.ExpectedXmlFiles", typeof(ExpectedXmlFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProjectGuid&gt;{F0CD4EDC-5873-4D81-9458-7CFBA3E49FE5}&lt;/ProjectGuid&gt;.
        /// </summary>
        internal static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FirstLevel /&gt;
        ///
        ///&lt;FirstLevel&gt;
        ///  &lt;SecondLevel
        ///    FirstAttributeName=&quot;FirstAttributeValue&quot;
        ///    SecondAttributeName=&quot;SecondAttributeValue&quot; /&gt;
        ///  &lt;FirstLevel
        ///    WithSome=&quot;Attribute&quot; /&gt;
        ///&lt;/FirstLevel&gt;
        ///
        ///&lt;FirstLevel
        ///  WithSome=&quot;Attribute&quot; /&gt;.
        /// </summary>
        internal static string FirstLevel {
            get {
                return ResourceManager.GetString("FirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;FirstLevelNoNamespace /&gt;
        ///
        ///&lt;FirstLevelNoNamespace
        ///  WithSome=&quot;Attribute&quot; /&gt;.
        /// </summary>
        internal static string FirstLevelNoNamespace {
            get {
                return ResourceManager.GetString("FirstLevelNoNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;n:FirstLevelWithNNamespace&gt;
        ///  &lt;m:SecondLevelWithMNamespace
        ///    FirstAttributeName=&quot;FirstAttributeValue&quot;
        ///    SecondAttributeName=&quot;SecondAttributeValue&quot; /&gt;
        ///  &lt;FirstLevelNoNamespace
        ///    WithSome=&quot;Attribute&quot; /&gt;
        ///&lt;/n:FirstLevelWithNNamespace&gt;.
        /// </summary>
        internal static string FirstLevelWithNamespace {
            get {
                return ResourceManager.GetString("FirstLevelWithNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SecondLevel
        ///  FirstAttributeName=&quot;FirstAttributeValue&quot;
        ///  SecondAttributeName=&quot;SecondAttributeValue&quot; /&gt;.
        /// </summary>
        internal static string SecondLevel {
            get {
                return ResourceManager.GetString("SecondLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;m:SecondLevelWithMNamespace
        ///  FirstAttributeName=&quot;FirstAttributeValue&quot;
        ///  SecondAttributeName=&quot;SecondAttributeValue&quot; /&gt;.
        /// </summary>
        internal static string SecondLevelWithNamespace {
            get {
                return ResourceManager.GetString("SecondLevelWithNamespace", resourceCulture);
            }
        }
    }
}
