//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projbook.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceXmlFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceXmlFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projbook.Tests.Resources.SourceXmlFiles", typeof(SourceXmlFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;14.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(SolutionDir)build\Projbook.settings&quot; Condition=&quot;Exists(&apos;$(SolutionDir)build\Projbook.settings&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProjectGuid&gt;{F0CD4EDC-5873-4D81-9458-7CFBA3E49FE5}&lt;/ProjectGuid&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CoreCsproj {
            get {
                return ResourceManager.GetString("CoreCsproj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RootNode xmlns=&quot;DefaultNamespace&quot; xmlns:n=&quot;NNamespace&quot; xmlns:m=&quot;MNamespace&quot;&gt;
        ///  &lt;FirstLevelNoNamespace/&gt;
        ///  &lt;n:FirstLevelWithNNamespace&gt;
        ///    &lt;m:SecondLevelWithMNamespace FirstAttributeName=&quot;FirstAttributeValue&quot; SecondAttributeName=&quot;SecondAttributeValue&quot;/&gt;
        ///    &lt;FirstLevelNoNamespace WithSome=&quot;Attribute&quot;/&gt;
        ///  &lt;/n:FirstLevelWithNNamespace&gt;
        ///&lt;/RootNode&gt;.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RootNode&gt;
        ///  &lt;FirstLevel/&gt;
        ///  &lt;FirstLevel&gt;
        ///    &lt;SecondLevel FirstAttributeName=&quot;FirstAttributeValue&quot; SecondAttributeName=&quot;SecondAttributeValue&quot;/&gt;
        ///    &lt;FirstLevel WithSome=&quot;Attribute&quot;/&gt;
        ///  &lt;/FirstLevel&gt;
        ///&lt;/RootNode&gt;.
        /// </summary>
        internal static string SimpleNoNamespace {
            get {
                return ResourceManager.GetString("SimpleNoNamespace", resourceCulture);
            }
        }
    }
}
