//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projbook.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceCSharpFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceCSharpFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projbook.Tests.Resources.SourceCSharpFiles", typeof(SourceCSharpFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Projbook.Tests.Resources.SourcesA
        ///{
        ///    public class AnyClass
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string AnyClass {
            get {
                return ResourceManager.GetString("AnyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Projbook.Tests.Foo
        ///{
        ///    public class Foo
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string Foo {
            get {
                return ResourceManager.GetString("Foo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    
        ///
        ///    
        ///    // Some comments here
        ///
        ///    using System;
        ///
        ///    namespace Projbook.Tests.Resources.SourcesA
        ///    {
        ///        public class NeedCleanup
        ///        {
        ///            // Following is an empty line
        /// 
        ///            // That has to be kept without preventing the indent fix
        ///        }
        ///    }
        ///
        ///    // Some more fucky lines after
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string NeedCleanup {
            get {
                return ResourceManager.GetString("NeedCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Projbook.Tests.Resources.SourcesA
        ///{
        ///    public class Options
        ///    {
        ///        void Method()
        ///        {
        ///            // Some content
        ///        }
        ///
        ///        void EmptyMethod(string i){}
        ///
        ///        public int Property { get; set; }
        ///        
        ///        event Action Event
        ///        {
        ///            add
        ///            {
        ///                // Something
        ///            }
        ///            remove
        ///            {
        ///            }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace NS
        ///{
        ///    public class OneClassSomewhere
        ///    {
        ///        private class SubClass
        ///        {
        ///            public int WhateverProperty
        ///            {
        ///                get
        ///                {
        ///                    return 42;
        ///                }
        ///                set
        ///                {
        ///                    string foo = &quot;foo&quot;;
        ///                }
        ///            }
        ///        }
        ///
        ///        protected bool Foo(string fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
    }
}
