//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projbook.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TemplateFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projbook.Tests.Resources.TemplateFiles", typeof(TemplateFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Title&gt;@Model.Title&lt;/Title&gt;
        ///@foreach (var page in Model.Pages)
        ///{
        ///    &lt;Id&gt;@page.Id&lt;/Id&gt;
        ///    &lt;Title&gt;@page.Title&lt;/Title&gt;
        ///	&lt;PreSectionContent&gt;&lt;![CDATA[@(page.PreSectionContent)]]&gt;&lt;/PreSectionContent&gt;
        ///	&lt;Sections&gt;
        ///    @foreach (var section in page.Sections)
        ///    {
        ///        &lt;Section&gt;
        ///			&lt;Id&gt;@(section.Id)&lt;/Id&gt;
        ///			&lt;Title&gt;@(section.Title)&lt;/Title&gt;
        ///			&lt;Content&gt;
        ///				&lt;![CDATA[@(section.Content)]]&gt;
        ///			&lt;/Content&gt;
        ///        &lt;/Section&gt;
        ///	&lt;/Sections&gt;
        ///}.
        /// </summary>
        internal static string Malformated {
            get {
                return ResourceManager.GetString("Malformated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Title&gt;@Model.Title&lt;/Title&gt;
        ///@foreach (var page in Model.Pages)
        ///{
        ///    &lt;Id&gt;@page.Id&lt;/Id&gt;
        ///    &lt;Title&gt;@page.Title&lt;/Title&gt;
        ///	&lt;PreSectionContent&gt;&lt;![CDATA[@(page.PreSectionContent)]]&gt;&lt;/PreSectionContent&gt;
        ///	&lt;Sections&gt;
        ///    @foreach (var section in page.Sections)
        ///    {
        ///        &lt;Section&gt;
        ///			&lt;Id&gt;@(section.Id)&lt;/Id&gt;
        ///			&lt;Title&gt;@(section.Title)&lt;/Title&gt;
        ///			&lt;Content&gt;
        ///				&lt;![CDATA[@(section.Content)]]&gt;
        ///			&lt;/Content&gt;
        ///        &lt;/Section&gt;
        ///    }
        ///	&lt;/Sections&gt;
        ///}
        ///&lt;script&gt;
        ///        $div.filetree.foreach
        ///        (
        ///            $(functio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Title&gt;@Model.Title&lt;/Title&gt;
        ///@foreach (var page in Model.Pages)
        ///{
        ///    &lt;Id&gt;@page.Id&lt;/Id&gt;
        ///    &lt;Title&gt;@page.Title&lt;/Title&gt;
        ///	&lt;PreSectionContent&gt;&lt;![CDATA[@(page.PreSectionContent)]]&gt;&lt;/PreSectionContent&gt;
        ///	&lt;Sections&gt;
        ///    @foreach (var section in page.Sections)
        ///    {
        ///        &lt;Section&gt;
        ///			&lt;Id&gt;@(section.Id)&lt;/Id&gt;
        ///			&lt;Title&gt;@(section.Title)&lt;/Title&gt;
        ///			&lt;Content&gt;
        ///				@(section.Content)
        ///			&lt;/Content&gt;
        ///        &lt;/Section&gt;
        ///    }
        ///	&lt;/Sections&gt;
        ///}
        ///&lt;script&gt;
        ///	$(function () { 
        ///		$(&apos;.filetree&apos;).each(function(tree) {
        ///				$(this).jstr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Simple_filesystem {
            get {
                return ResourceManager.GetString("Simple_filesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Title&gt;@Model.Title - PDF&lt;/Title&gt;
        ///@foreach (var page in Model.Pages)
        ///{
        ///    &lt;Id&gt;@page.Id&lt;/Id&gt;
        ///    &lt;Title&gt;@page.Title&lt;/Title&gt;
        ///	&lt;PreSectionContent&gt;&lt;![CDATA[@(page.PreSectionContent)]]&gt;&lt;/PreSectionContent&gt;
        ///	&lt;Sections&gt;
        ///    @foreach (var section in page.Sections)
        ///    {
        ///        &lt;Section&gt;
        ///			&lt;Id&gt;@(section.Id)&lt;/Id&gt;
        ///			&lt;Title&gt;@(section.Title)&lt;/Title&gt;
        ///			&lt;Content&gt;
        ///				&lt;![CDATA[@(section.Content)]]&gt;
        ///			&lt;/Content&gt;
        ///        &lt;/Section&gt;
        ///    }
        ///	&lt;/Sections&gt;
        ///}.
        /// </summary>
        internal static string Simple_pdf {
            get {
                return ResourceManager.GetString("Simple_pdf", resourceCulture);
            }
        }
    }
}
